<html>
1. [개념] select의 기본 코드와 속성을 기본예제와 함께 설명하세요
<select> 태그로 감싸고, <option> 태그로 선택 항목을 정의한다.
속성: 
   - <select>: 콤보박스 전체를 감싸는 태그
   - <option>: 콤보박스 내의 각각의 선택 항목을 정의하는 태그
   - <optgroup>: 관련된 옵션들을 그룹화할 때 사용하는 태그
   - name 속성: 폼 데이터 전송 시 선택된 값을 식별하는 데 사용
   - value 속성: 각 옵션의 실제 값을 지정
   - selected 속성: 기본적으로 선택된 옵션을 지정
   - multiple 속성: 사용자가 여러 항목을 동시에 선택할 수 있도록 허용
   - label 태그: optgroup에 레이블을 제공하여 그룹의 의미를 명확히 함
예제)
<form action="result.jsp" method="post">
  <label for="fruit">좋아하는 과일:</label>
  <select name="fruit" id="fruit">
    <option value="apple">사과</option>
    <option value="banana">바나나</option>
    <option value="grape">포도</option>
  </select>
  <input type="submit" value="제출">
</form>


2. [실습] 좋아하는 계절 선택하기 : 해당 계절을 선택해서 특정한 rev.jsp 파일에 선택할 계절이 출력되게 하세요.
  * "당신이 가장 좋아하는 계절은?"이라는 질문과 함께 콤보박스를 만드세요.
  * 옵션으로는 '봄', '여름', '가을', '겨울'을 포함하세요.
  * `<select>` 태그의 `name` 속성값은 "season"으로 지정하세요.
<form action="rev.jsp">
  <label>
  <h3>좋아하는 계절 선택하기</h3>
  당신이 가장 좋아하는 계절은?
  <select name="season" id="season">
    <option value="봄">봄</option>
    <option value="여름">여름</option>
    <option value="가을">가을</option>
    <option value="겨울">겨울</option>
  </select>
  </label><br>
  <input type="submit" value="확인">
</form>


3. [실습] 나만의 도시락 만들기
   당신은 온라인 도시락 주문 페이지를 만들고 있습니다. 사용자가 여러 개의 반찬을 자유롭게 선택할 수 있도록, '오늘의 반찬' 목록을 다중 선택이 가능한 콤보 박스로 구현하세요.
   요구사항:
   **'오늘의 반찬'**이라는 제목의 콤보 박스를 만드세요.
   사용자가 Ctrl(Cmd) 키를 이용하여 여러 반찬을 동시에 선택할 수 있어야 합니다.
   선택 가능한 반찬으로는 '김치볶음', '계란말이', '소시지', '멸치볶음', '시금치무침'을 포함시키세요.
   선택 후 '주문' 버튼을 누르면 선택된 값들이 서버로 전송되도록 form 태그 안에 구성하세요.
<form action="order.jsp">
  <label>오늘의 반찬</label><br>
  <select name="side" multiple="multiple">
    <option>김치볶음</option>
    <option>계란말이</option>
    <option>소시지</option>
    <option>멸치볶음</option>
    <option>시금치무침</option>
  </select>
  <br><br>
  <input type="submit" value="주문">
</form>


4. [개념] select에서 optgroup을 사용하는 이유를 기본예제와 함께 설명하세요..
   optgroup은 관련된 옵션들을 그룹화할 때 사용하는 태그이다
    <select name="car">
        <optgroup label="국산차">
            <option value="hyundai">현대</option>
            <option value="kia">기아</option>
        </optgroup>
        <optgroup label="수입차">
            <option value="bmw">BMW</option>
            <option value="benz">Benz</option>
        </optgroup>
    </select>


5. [실습] 여행 상품 예약
   여행사 웹사이트에서 사용자가 여행지를 대륙별로 쉽게 선택할 수 있는 드롭다운 메뉴를 만들어 보세요. 아시아, 유럽, 북미 대륙으로 그룹을 나누어 각 대륙의 대표 도시들을 옵션으로 제공해야 합니다.
   요구사항:
   '아시아', '유럽', '북미' 3개의 **<optgroup>**을 만드세요.
   각 그룹에 아래의 도시들을 옵션으로 추가하세요.
   아시아: 서울, 도쿄, 방콕
   유럽: 파리, 로마, 런던
   북미: 뉴욕, LA, 밴쿠버
   '로마'를 선택하면 화면에는 '로마'로 보이지만, 서버에는 **'ROME'**이라는 영문 데이터가 전송되도록 설정하세요.
<form action="travel.jsp">
  <label for="city">여행지를 선택하세요:</label><br>
  <select name="city" id="city">
    <optgroup label="아시아">
      <option value="SEOUL">서울</option>
      <option value="TOKYO">도쿄</option>
      <option value="BANGKOK">방콕</option>
    </optgroup>
    <optgroup label="유럽">
      <option value="PARIS">파리</option>
      <option value="ROME">로마</option> 
      <option value="LONDON">런던</option>
    </optgroup>
    <optgroup label="북미">
      <option value="NEWYORK">뉴욕</option>
      <option value="LA">LA</option>
      <option value="VANCOUVER">밴쿠버</option>
    </optgroup>
  </select>
  <input type="submit" value="예약하기">
</form>


6. [개념] 컬러 피커란 무엇인지 오늘 input type="color"의 기본 예제를 통해서 설명하세요.
컬러피커는 사용자가 색상을 선택할 수 있도록 컬러 팔레트를 제공한다.
예시)
<form>
  <label for="favcolor">좋아하는 색상을 선택하세요:</label>
  <input type="color" id="favcolor" name="favcolor" value="#ff0000">
  <input type="submit" value="확인">
</form>

 <database>
1. [개념] LPAD, RPAD 함수의 기본적인 형식을 선언하고 각 속성들의 의미를 기술하세요.
기본형식: 
LPAD(문자열, 전체길이, 채울문자)
RPAD(문자열, 전체길이, 채울문자)

문자열: 길이를 맞추고 싶은 데이터
전체 길이: 만들고 싶은 총 길이
채울 문자: 빈 공간에 채울 문자

2. [실습] 숫자 '123'을 항상 7자리로 표현하고 싶습니다. 비어있는 왼쪽 공간을 '0'으로 채워 '00123'으로 만들어보세요. (사원번호, 학번 등에 자주 사용돼요\!)
SELECT LPAD('123', 7, '0') FROM DUAL;

3. [실습] EMP의 사원번호(총7자리 왼쪽 0000), 부서번호(총 4자리 오른쪽 0000), 이름(총 12자리 왼쪽 # 처리) 해서 표현하세요
SELECT 
  LPAD(EMPNO, 7, '0') AS 사원번호,
  RPAD(DEPTNO, 4, '0') AS 부서번호,
  LPAD(ENAME, 12, '#') AS 이름
FROM EMP;

4. [개념] RTRIM, LTRIM, TRIM의 차이점을 기본 예제를 통해서 설명하세요.
LTRIM(Left TRIM) : 왼쪽의 불필요한 부분 잘라냄
RTRIM(Right TRIM) : 오른쪽의 불필요한 부분 잘라냄
TRIM : 양쪽 모두를 잘라내거나, 특정 방향의 특정 문자 하나를 지정해서 잘라냄

SELECT LTRIM('***HELLO', '*') FROM DUAL; -- 결과: HELLO
SELECT RTRIM('HELLO***', '*') FROM DUAL; -- 결과: HELLO
SELECT TRIM('=' FROM '=HELLO=') FROM DUAL; -- 결과: HELLO

5. [실습] 복합 상품 코드 정제하기
   문제: 오래된 재고 시스템의 상품 코드 앞부분에는 공백(     ), 별표(*), 숫자 영(0)이 뒤죽박죽 섞여 있습니다. LTRIM 함수를 단 한 번만 사용하여 이 모든 불필요한 접두사를 제거하고, '7-BOND' 처럼 의미 있는 코드 부분만 남겨보세요.
   대상 데이터: '  *007-BOND'
   결과 데이터: '7-BOND'
SELECT LTRIM('  *007-BOND', ' *0') FROM DUAL;

6. [실습] 사용자가 아이디를 '  ==user01==  ' 와 같이 잘못 입력했습니다. 아이디의 규칙은 양쪽에 공백과 = 기호가 없어야 한다고 가정합니다. 함수를 중첩으로 사용하여 순수한 아이디 'user01'만 정확하게 추출하는 SQL을 작성하세요.
SELECT TRIM('=' FROM TRIM(' ' FROM '  ==user01==  '))
FROM DUAL;

7. [개념] 날짜 ==> 문자열 전환 함수의 속성값들을 기본예제와 함께 설명하세요.
속성값:
    - 'YYYY' : 4자리 연도
    - 'MM' : 월
    - 'DD' : 일
    - 'HH24' : 24시간 형식
    - 'MI' : 분
    - 'SS' : 초
* 문자열로 변환은 TO_CHAR()
  
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

8. [개념] 숫자 ==> 문자열 전환 함수의 속성값들을 기본예제와 함께 설명하세요.
속성값:
    - '9' : 숫자 한 자를 의미.
    - '0' : 빈 자리를 0으로 채움 
  
SELECT TO_CHAR(12345.6, '9,999.00') FROM DUAL; 

9.  [실습]
    1) 모든 직원의 입사일을 '2023년 10월 13일 (금요일)'과 같은 형식으로 출력해보세요.
    SELECT TO_CHAR(HIREDATE, 'YYYY"년" MM"월" DD"일" (DAY)') 
    FROM EMP;

    2) 모든 직원의 월급 SAL '$99,999.00'과 같이 달러 기호, 천 단위 쉼표, 그리고 소수점 둘째 자리까지 항상 표시되도록 출력해보세요. (소수점 아래 값이 없어도 .00으로 나와야 해요!)
    SELECT TO_CHAR(SAL, '$99,999.00')
    FROM EMP;