> 1단계

<html>
1. [개념] a link와 iframe의 연동 관계를 기본예제와 속성을 통해서 설명하세요
   a 태그의 target 속성과 iframe의 name속성을 일치 시키면, 클릭 시 iframe안에서 페이지가 열림.
   ex) 
<a href="page1.html" target="contentFrame">Page</a>
<iframe src="welcome.html" name="contentFrame" width="600" height="400"></iframe>

2. [실습] 같은 경로, 내부페이지에 2개의 페이지를 만들고(컴퓨터판매사이트, 전자제품판매사이트), 
     하나는 외부페이지 2개를 만들고(https://phet.colorado.edu/, https://www.wikipedia.org/)
     iframe과 a href로 클릭시, 이동되게 처리하세요.
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>iframe 연동 예제</title>
</head>
<body>
    <a href="computer.html" target="mainFrame">컴퓨터 판매</a> 
    <a href="electronics.html" target="mainFrame">전자제품 판매</a>

    <a href="https://phet.colorado.edu/" target="mainFrame">PHET</a>
    <a href="https://www.wikipedia.org/" target="mainFrame">위키피디아</a>

    <iframe src="welcome.html" name="mainFrame" width="800" height="500"></iframe>
</body>
</html>


3. [개념] form의 여러가지 속성의 의미와 하위 요소객체들을 기본예제를 통해 기술하세요.
form의 속성에는 action, method가 있다.
action은 데이터를 전송할 서버를 지정하는거고, method는 데이터 전송 방식을 get/post중에 지정하는 거다.
하위요소에는 input, label, textarea 등이 있다.
EX)
<form action="signup.jsp" method="post">
    아이디: <input type="text" name="userid"><br>
    비밀번호: <input type="password" name="userpw"><br>
    자기소개: <textarea name="intro"></textarea><br>
    <input type="submit" value="회원가입">
</form>


4. [실습] 회원가입화면을 만들고, 이 화면에서 데이터를 받는 .jsp를 만들어 회원아이디와 회원이름을 받는 처리를 하세요.
<!-- 회원가입 화면 -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>회원가입</title>
</head>
<body>
    <h2>회원가입</h2>
    <form action="signup.jsp" method="post">
        아이디: <input type="text" name="userid"><br>
        이름: <input type="text" name="username"><br>
        <input type="submit" value="가입하기">
    </form>
</body>
</html>
<!-- signup.jsp -->
<%@ page contentType="text/html; charset=UTF-8" %>
<html>
<body>
<%
    String id = request.getParameter("userid");
    String name = request.getParameter("username");
%>
<h3>회원가입 완료</h3>
아이디: <%= id %><br>
이름: <%= name %><br>
</body>
</html>


<database>
1. [개념] 테이블 컬럼 삭제와 컬럼명 변경을 기본형식을 설명하세요..
컬럼 삭제:
ALTER TABLE 테이블명 DROP COLUMN 컬럼명;

컬럼명 변경:
ALTER TABLE 테이블명 RENAME COLUMN 기존컬럼명 TO 바꿀컬럼명;

2. [실습] 
   -- PLAYER 테이블 생성
   CREATE TABLE PLAYER (
       PLAYER_ID    NUMBER(5) PRIMARY KEY,
       PLAYER_NAME  VARCHAR2(30),
       HEIGHT       NUMBER(5, 1),
       WEIGHT       NUMBER(5, 1)
   );
   PLAYER 테이블에 선수들의 키(HEIGHT)와 몸무게(WEIGHT) 컬럼이 있습니다. BMI(체질량지수)를 계산하여 PLAYER_BMI라는 새로운 컬럼에 저장하기로 했습니다. 더 이상 개별 키와 몸무게 데이터는 필요 없어져 두 컬럼을 한 번에 삭제하려고 합니다. PLAYER 테이블에서 HEIGHT와 WEIGHT 컬럼을 삭제하는 SQL 문을 작성하세요.    
   -- ORDERS 테이블 생성
   CREATE TABLE ORDERS (
       ORDER_ID    NUMBER(10) PRIMARY KEY,
       CUSTOMER_ID NUMBER(10),
       ORDER_DT    DATE
   );   
        ORDERS 테이블에 주문 날짜를 기록하는 ORDER_DT 컬럼이 있습니다. 관리자가 날짜 형식을 명확하게 인지할 수 있도록 ORDER_DT 컬럼의 이름을 ORDER_DATE로 변경하는 SQL 문을 작성하세요.

ALTER TABLE PLAYER DROP COLUMN HEIGHT;
ALTER TABLE PLAYER DROP COLUMN WEIGHT;

ALTER TABLE ORDERS RENAME COLUMN ORDER_DT TO ORDER_DATE;

3. [개념] DELETE에 의한 삭제와 TRUNCATE에 의한 삭제를 기본 예제를 통하여 차이점을 기술하세요.
DELETE는 조건에 맞는 행만 삭제 가능하고 롤백이 가능하지만, TRUNCATE는 전체 행을 삭제하고 롤백이 불가능하다.
EX)
DELETE FROM EMP WHERE DEPTNO = 10;
TRUNCATE TABLE EMP;

4. [실습] EMP10테이블을 복사테이블 생성, 컬럼추가, 컬럼변경, 컬럼명 변경, 컬럼삭제, TRUNCATE에 의한 삭제, 테이블명변경, 테이블 삭제등의
   일련 과정으로 진행하고, 해당 SQL을 여기에 붙여 넣으세요..

CREATE TABLE EMP10 AS SELECT * FROM EMP;

ALTER TABLE EMP10 ADD (EMAIL VARCHAR2(20));

ALTER TABLE EMP10 MODIFY (ENAME VARCHAR2(50));

ALTER TABLE EMP10 RENAME COLUMN ENAME TO EMP_NAME;

ALTER TABLE EMP10 DROP COLUMN EMAIL;

TRUNCATE TABLE EMP10;

ALTER TABLE EMP10 RENAME TO EMP_TEMP;

DROP TABLE EMP_TEMP;


5. [개념] oracle 함수 중, 대소문자를 변경해주는 함수를 간단한 예제를 통해서 기술하세요.
UPPER(대문자 변환)와 LOWER(소문자 변환)함수가 있다.
EX) 
SELECT UPPER(GROUP_NAME) FROM IDOL;
SELECT LOWER(GROUP_NAME) FROM IDOL;

6. [실습] substr함수를 이용하여 job을 2번째부터 3번째까지 잘라서 출력하세요..
SELECT SUBSTR(job, 2, 3)
FROM EMP;

7. [개념] length(), lengthb()의 차이점을 기술하세요
length()과 lenghtb()의 차이점은 단위의 차이이다. 
length는 문자열의 글자수이고, lengthb는 문자열의 바이트 수이다.

8. [실습] KPOP_IDOLS 테이블의 모든 그룹에 대해, **GROUP_NAME**의 **글자 수 (LENGTH)**와 **바이트 수 (LENGTHB)**를 조회하고, 두 값의 차이도 함께 출력하세요. (대부분의 Oracle 환경에서 한글은 글자 수보다 바이트 수가 2~3배 더 큽니다.)
SELECT GROUP_NAME,
       LENGTH(GROUP_NAME),
       LENGTHB(GROUP_NAME),
       (LENGTHB(GROUP_NAME) - LENGTH(GROUP_NAME))
FROM KPOP_IDOLS;

9.  [실습] KPOP_IDOLS 테이블에서 **AGENCY**의 **바이트 수 (LENGTHB)**가 가장 큰 순서대로 그룹 이름과 소속사를 출력하세요. (소속사 이름의 바이트 길이가 긴 그룹을 찾아보세요.)
SELECT GROUP_NAME, AGENCY, LENGTHB(AGENCY)
FROM KPOP_IDOLS
ORDER BY LENGTHB(AGENCY) DESC;