### HTML 문제

**1. HTML에서 `<p>` 태그의 주요 기능은 무엇인가요?**<br>
a) 수평선을 만듭니다.<br>
b) 텍스트를 굵게 만듭니다.<br>
<u>c) 위아래에 약간의 공백이 있는 단락을 만듭니다.<br></u>
d) 한 줄을 띄웁니다.

---
 
**2. HTML 문서에서 주제를 구분하는 수평선을 만들 때 사용되는 태그는 무엇인가요?**<br>
a) `<br>`<br>
b) `<line>`<br>
c) `<strong>`<br>
<u>d) `<hr>`</u>

---

**3. 새로운 단락을 시작하지 않고 단락 내에서 줄을 바꾸려면 어떤 태그를 사용해야 하나요?**<br>
a) `<p>`<br>
b) `<hr>`<br>
<u>c) `<br>`<br></u>
d) `<pre>`

---

**4. HTML에서 `&lt;`나 `&gt;`와 같은 엔티티(entity)를 사용해야 하는 이유는 무엇인가요?**<br>
a) 텍스트를 굵고 기울임꼴로 동시에 만들기 위해.<br>
<u>b) 브라우저가 `<`나 `>` 같은 특수 문자를 HTML 태그로 해석하는 것을 방지하기 위해.<br></u>
c) 텍스트에 추가 공백을 만들기 위해.<br>
d) 강조를 위해 텍스트에 밑줄을 긋기 위해.

---

**5. 웹 페이지에 "AT&T"라는 텍스트를 올바르게 표시하려면 어떻게 해야 하나요?**<br>
a) `AT<and>T`<br>
b) `AT&T`<br>
<u>c) `AT&amp;T`<br></u>
d) `AT&&T`

---

**6. 공백과 줄 바꿈을 그대로 보존해야 하는 코드 블록이나 아스키 아트를 표시하는 데 가장 적합한 태그는 무엇인가요?**<br>
a) `<p>`<br>
b) `<code>`<br>
c) `<div>`<br>
<u>d) `<pre>`</u>

---

**7. 제시된 본문에 따르면, `<b>`와 `<strong>`의 의미론적 차이는 무엇인가요?**<br>
a) 차이가 없으며, 둘 다 텍스트를 굵게 만듭니다.<br>
b) `<b>`는 제목용이고, `<strong>`는 단락용입니다.<br>
<u>c) `<b>`는 단순히 텍스트를 시각적으로 굵게 만들지만, `<strong>`는 내용이 중요하다는 것을 나타냅니다.<br></u>
d) `<strong>`는 텍스트를 굵게 만드는 것 외에 강조 색상도 추가합니다.

---

**8. 더 이상 정확하지 않거나 삭제된 텍스트임을 나타내는 데 사용되는 태그 쌍은 무엇인가요?**<br>
a) `<i>`와 `<em>`<br>
b) `<b>`와 `<strong>`<br>
c) `<u>`와 `<hr>`<br>
<u>d) `<s>`와 `<del>`</u>

---

**9. HTML 단락에 여러 개의 연속된 공백을 표시하려면 어떻게 해야 하나요?**<br>
a) 스페이스바를 여러 번 누릅니다.<br>
b) `<space>` 태그를 사용합니다.<br>
<u>c) 각 공백에 대해 `&nbsp;` 엔티티를 사용합니다.<br></u>
d) `<p>` 태그 안에 `<pre>` 태그를 사용합니다.

---

**10. 강조의 목적이 아닌, 기술 용어나 외국어처럼 문체상 구분을 위해 텍스트를 기울임꼴로 만드는 태그는 무엇인가요?**<br>
a) `<em>`<br>
<u>b) `<i>`<br></u>
c) `<b>`<br>
d) `<p>`

***

### SQL 문제

**11. 제공된 SQL 예제에서, 문자열과 컬럼 값을 결합하여 하나의 출력 문자열로 만드는 데 사용된 연산자는 무엇인가요?**<br>
a) `+`<br>
b) `&`<br>
<u>c) `||`<br></u>
d) `CONCAT()`

---

**12. `SELECT` 문에서 `"사원정보"`와 같이 큰따옴표를 사용하는 목적은 무엇인가요?**<br>
a) 해당 문자열을 기준으로 결과를 필터링하기 위해.<br>
<u>b) 출력 결과의 컬럼에 사용자 정의 이름(별칭)을 지정하기 위해.<br></u>
c) 쿼리가 텍스트 기반 검색임을 나타내기 위해.<br>
d) SQL 코드 내에 주석을 강조하기 위해.

---

**13. `SELECT` 문에서 `WHERE` 절의 주요 기능은 무엇인가요?**<br>
a) 결과 행을 정렬합니다.<br>
b) 동일한 값을 가진 행을 그룹화합니다.<br>
<u>c) 지정된 조건에 따라 행을 필터링합니다.<br></u>
d) 표시할 열을 선택합니다.

---

**14. 직책(`JOB`)이 'CLERK'인 사원의 모든 정보를 올바르게 선택하는 쿼리는 무엇인가요?**<br>
a) `SELECT * FROM EMP WHERE JOB <> 'CLERK';`<br>
<u>b) `SELECT * FROM EMP WHERE JOB = 'CLERK';`<br></u>
c) `SELECT * FROM EMP IF JOB = 'CLERK';`<br>
d) `SELECT * FROM EMP JOB IS 'CLERK';`

---

**15. 본문에 따르면, SQL 쿼리의 어떤 부분이 대소문자를 구분하나요?**<br>
a) `SELECT`, `FROM`, `WHERE`와 같은 SQL 키워드.<br>
b) `EMP`와 같은 테이블 이름.<br>
c) `ENAME`, `JOB`과 같은 컬럼 이름.<br>
<u>d) 'SMITH'와 같이 컬럼 내의 실제 데이터 값.</u>

---

**16. 급여(`SAL`)가 2500 이상인 직원을 어떻게 선택할 수 있나요?**<br>
a) `SELECT * FROM EMP WHERE SAL > 2500;`<br>
b) `SELECT * FROM EMP WHERE SAL == 2500;`<br>
<u>c) `SELECT * FROM EMP WHERE SAL >= 2500;`<br></u>
d) `SELECT * FROM EMP WHERE SAL=> 2500;`

---

**17. 본문에서 "같지 않다"를 의미하는 두 가지 다른 연산자는 무엇인가요?**<br>
a) `!=` 와 `!==`<br>
<u>b) `<>` 와 `!=`<br></u>
c) `NOT` 와 `!==`<br>
d) `<>` 와 `~=`

---

**18. 직책이 'MANAGER'이면서 급여가 2500 이상인 직원을 찾는 쿼리는 무엇인가요?**<br>
a) `SELECT * FROM EMP WHERE JOB = 'MANAGER' OR SAL >= 2500;`<br>
<u>b) `SELECT * FROM EMP WHERE JOB = 'MANAGER' AND SAL >= 2500;`<br></u>
c) `SELECT * FROM EMP WHERE JOB = 'MANAGER' & SAL >= 2500;`<br>
d) `SELECT * FROM EMP WHERE JOB = 'MANAGER', SAL >= 2500;`

---

**19. `SELECT * FROM EMP WHERE DEPTNO = 10;` 쿼리의 결과는 무엇인가요?**<br>
a) 모든 부서의 모든 직원을 나열합니다.<br>
b) 10번 부서의 부서 이름만 나열합니다.<br>
<u>c) 10번 부서에 속한 모든 직원의 모든 정보를 나열합니다.<br></u>
d) 10번 부서에 속하지 않은 직원을 나열합니다.

---

**20. 예제를 바탕으로, 리터럴 문자열(literal string)과 컬럼 값을 출력에서 어떻게 결합하나요?**<br>
a) `SELECT '나의 사원번호는 ', EMPNO FROM EMP;`<br>
b) `SELECT '나의 사원번호는 ' + EMPNO FROM EMP;`<br>
<u>c) `SELECT '나의 사원번호는 ' || EMPNO FROM EMP;`<br></u>
d) `SELECT "나의 사원번호는 " EMPNO FROM EMP;`